run_mode: kReal
trigger_mode: kManual
init_motion_enable: false
planner_trigger_lead_time: 1.5 #1.5  1.5_pure  5.0_mpc
smooth_heading_enable: true
init_motion:
  z_takeoff: 2.0  ####2.0
  z_drop: 0.5
  x_forward: 0.0

# Group related parameters to be shared between nodes.
RobotDynamics:
  v_max: 1.2 ##0.5 ##0.5
  v_init_max: 0.5
  v_homing_max: 1.5
  yaw_rate_max: 0.1
  dt: 0.05

world_frame_id : map