<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:macro name="accessories" params="base_name base_length base_height  " >

          <xacro:include filename="$(find hector_sensors_description)/urdf/hokuyo_utm30lx.urdf.xacro" /> 
        <xacro:include filename="$(find hector_sensors_description)/urdf/asus_camera.urdf.xacro" />
       <xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/>

       <xacro:include filename="$(find realsense_ros_gazebo)/xacro/depthcam.xacro"/>
       
  <!-- /2 +0.04    -->
       
           <!-- <xacro:hokuyo_utm30lx 
            name="hokuyo" 
            parent="${base_name}" 
            ros_topic="scan" 
            update_rate="30" 
            ray_count="1040" 
            min_angle="130" 
            max_angle="-130" >
            <origin xyz="0.0 0.0 ${base_height/2+0.1}" rpy="0 0 0"/>       
        </xacro:hokuyo_utm30lx> -->

           <!-- VLP-16 -->
        <!-- <xacro:VLP-16 parent="${base_name}" name="velodyne" topic="velodyne_points" hz="10" samples="1024" gpu="false" lasers="16" max_range="300">
            <origin xyz="0.20  0 ${base_height/2}" rpy="0 0 0" />
        </xacro:VLP-16>  -->

         <!-- VHDL-32E -->
        <xacro:include filename="$(find velodyne_description)/urdf/HDL-32E.urdf.xacro"/>
        <HDL-32E parent="${base_name}" name="velodyne" topic="/velodyne_points" hz="10" samples="1024" gpu="true">
          <origin xyz="0.0  0  ${base_height/2}"  rpy="0 0 0" />
        </HDL-32E>



           <!-- <xacro:realsense_d435 sensor_name="d435" parent_link="${base_name}" rate="10">
            <origin rpy="0 0 0 " xyz="0 0 0.5"/>
          </xacro:realsense_d435> -->
         
      

 
        <xacro:asus_camera 
            parent="${base_name}" 
            name="camera">
            <origin xyz="${base_length / 2} 0.0 -${base_height / 2 + 0.01}" rpy="0 0 0"/>
        </xacro:asus_camera>

        <gazebo>
            <plugin name="imu_controller" filename="libhector_gazebo_ros_imu.so">
                <updateRate>50.0</updateRate>
                <bodyName>imu_link</bodyName>
                <topicName>imu/data</topicName>
                <accelDrift>0.005 0.005 0.005</accelDrift>
                <accelGaussianNoise>0.005 0.005 0.005</accelGaussianNoise>
                <rateDrift>0.005 0.005 0.005 </rateDrift>
                <rateGaussianNoise>0.005 0.005 0.005 </rateGaussianNoise>
                <headingDrift>0.005</headingDrift>
                <headingGaussianNoise>0.005</headingGaussianNoise>
            </plugin>
        </gazebo>

        <link name="imu_link">
            <inertial>
                <mass value="0.001"/>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <inertia ixx="1e-09" ixy="0.0" ixz="0.0" iyy="1e-09" iyz="0.0" izz="1e-09"/>
            </inertial>
        </link>
        <joint name="imu_joint" type="fixed">
            <parent link="${base_name}" />
            <child link="imu_link" />
        </joint>

       <!--

        <xacro:include filename="$(find champ_arm_description)/urdf/champ_arm.urdf.xacro" />
        <xacro:champ_arm parent="${base_name}">
            <origin xyz="0.07 0.0 ${base_height / 2}" rpy="0 0 0"/>
        </xacro:champ_arm> -->
    </xacro:macro>
</robot>
